import type { TicketStatus, TicketLinkType, TicketLink, TicketPriority, TicketType, GitHubIssueMetadata, ConversationMode, EffortLevel } from '@fleex/shared';
import { BoardEntity } from '../../../domain/entities/board.entity.js';
import { TicketEntity } from '../../../domain/entities/ticket.entity.js';
import { TicketActivityEntity } from '../../../domain/entities/ticket-activity.entity.js';
import type { TicketStorePort } from '../../../application/ports/ticket-store.port.js';
import type { PgConnection } from './connection.js';

const MAX_ACTIVITY_ENTRIES = 5000;

export class PgTicketStore implements TicketStorePort {
  constructor(private readonly db: PgConnection) {}

  // ── Boards ──

  async getAllBoards(): Promise<BoardEntity[]> {
    const { rows } = await this.db.query('SELECT * FROM boards');
    return rows.map(rowToBoard);
  }

  async getBoardById(id: string): Promise<BoardEntity | null> {
    const { rows } = await this.db.query('SELECT * FROM boards WHERE id = $1', [id]);
    return rows.length > 0 ? rowToBoard(rows[0]) : null;
  }

  async saveBoard(board: BoardEntity): Promise<void> {
    await this.db.query(
      `INSERT INTO boards (id, name, emoji, created_at, updated_at)
       VALUES ($1,$2,$3,$4,$5)
       ON CONFLICT (id) DO UPDATE SET
         name = $2,
         emoji = $3,
         created_at = $4,
         updated_at = $5`,
      [
        board.id,
        board.name,
        board.emoji,
        board.createdAt.toISOString(),
        board.updatedAt.toISOString(),
      ],
    );
  }

  async removeBoard(id: string): Promise<void> {
    await this.db.query('DELETE FROM boards WHERE id = $1', [id]);
  }

  // ── Tickets ──

  async createTicket(ticket: TicketEntity): Promise<void> {
    // display_id is generated by the tickets_display_id_seq sequence
    // (DEFAULT nextval(...) set on the column by migration 016).
    const { rows } = await this.db.query(
      `INSERT INTO tickets (
        id, board_id, title, description, status, priority, type, position,
        tags, links, blocked, favorite, due_date, assignee,
        agent_claimed_at, github_metadata, archived_at, first_doing_at, status_changed_at, created_at, updated_at
      ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)
      RETURNING display_id`,
      [
        ticket.id,
        ticket.boardId,
        ticket.title,
        ticket.description,
        ticket.status,
        ticket.priority,
        ticket.type,
        ticket.position,
        JSON.stringify(ticket.tags),
        JSON.stringify(ticket.links),
        ticket.blocked,
        ticket.favorite,
        ticket.dueDate?.toISOString() ?? null,
        ticket.assignee,
        ticket.agentClaimedAt?.toISOString() ?? null,
        ticket.githubMetadata ? JSON.stringify(ticket.githubMetadata) : null,
        ticket.archivedAt?.toISOString() ?? null,
        ticket.firstDoingAt?.toISOString() ?? null,
        ticket.statusChangedAt.toISOString(),
        ticket.createdAt.toISOString(),
        ticket.updatedAt.toISOString(),
      ],
    );
    if (rows.length === 0) throw new Error('createTicket failed to return display_id');
    ticket.displayId = rows[0].display_id as number;
  }


  async getAllTickets(): Promise<TicketEntity[]> {
    const { rows } = await this.db.query('SELECT * FROM tickets WHERE archived_at IS NULL');
    return rows.map(rowToTicket);
  }

  async getTicketById(id: string): Promise<TicketEntity | null> {
    const { rows } = await this.db.query('SELECT * FROM tickets WHERE id = $1', [id]);
    return rows.length > 0 ? rowToTicket(rows[0]) : null;
  }

  async getTicketByDisplayId(displayId: number): Promise<TicketEntity | null> {
    // No `archived_at IS NULL` filter — display ids are globally unique and this
    // lookup must reach archived tickets (used by `ticket unarchive`).
    const { rows } = await this.db.query('SELECT * FROM tickets WHERE display_id = $1', [displayId]);
    return rows.length > 0 ? rowToTicket(rows[0]) : null;
  }

  async getTicketsByBoard(boardId: string): Promise<TicketEntity[]> {
    const { rows } = await this.db.query(
      'SELECT * FROM tickets WHERE board_id = $1 AND archived_at IS NULL ORDER BY position ASC',
      [boardId],
    );
    return rows.map(rowToTicket);
  }

  async getTicketsByStatus(boardId: string, status: TicketStatus): Promise<TicketEntity[]> {
    const { rows } = await this.db.query(
      'SELECT * FROM tickets WHERE board_id = $1 AND status = $2 AND archived_at IS NULL ORDER BY position ASC',
      [boardId, status],
    );
    return rows.map(rowToTicket);
  }

  async getTicketsLinkedTo(type: TicketLinkType, ref: string): Promise<TicketEntity[]> {
    const { rows } = await this.db.query(
      `SELECT * FROM tickets WHERE links @> $1::jsonb`,
      [JSON.stringify([{ type, ref }])],
    );
    return rows.map(rowToTicket);
  }

  async saveTicket(ticket: TicketEntity): Promise<void> {
    await this.db.query(
      `INSERT INTO tickets (
        id, board_id, display_id, title, description, status, priority, type, position,
        tags, links, blocked, favorite, due_date, assignee,
        agent_claimed_at, github_metadata, archived_at, first_doing_at, status_changed_at,
        conversation_mode, model_override, effort_override, fast_mode, created_at, updated_at
      ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26)
      ON CONFLICT (id) DO UPDATE SET
        board_id = $2,
        display_id = $3,
        title = $4,
        description = $5,
        status = $6,
        priority = $7,
        type = $8,
        position = $9,
        tags = $10,
        links = $11,
        blocked = $12,
        favorite = $13,
        due_date = $14,
        assignee = $15,
        agent_claimed_at = $16,
        github_metadata = $17,
        archived_at = $18,
        first_doing_at = $19,
        status_changed_at = $20,
        conversation_mode = $21,
        model_override = $22,
        effort_override = $23,
        fast_mode = $24,
        created_at = $25,
        updated_at = $26`,
      [
        ticket.id,
        ticket.boardId,
        ticket.displayId,
        ticket.title,
        ticket.description,
        ticket.status,
        ticket.priority,
        ticket.type,
        ticket.position,
        JSON.stringify(ticket.tags),
        JSON.stringify(ticket.links),
        ticket.blocked,
        ticket.favorite,
        ticket.dueDate?.toISOString() ?? null,
        ticket.assignee,
        ticket.agentClaimedAt?.toISOString() ?? null,
        ticket.githubMetadata ? JSON.stringify(ticket.githubMetadata) : null,
        ticket.archivedAt?.toISOString() ?? null,
        ticket.firstDoingAt?.toISOString() ?? null,
        ticket.statusChangedAt.toISOString(),
        ticket.conversationMode,
        ticket.modelOverride,
        ticket.effortOverride,
        ticket.fastMode,
        ticket.createdAt.toISOString(),
        ticket.updatedAt.toISOString(),
      ],
    );
  }

  async removeTicket(id: string): Promise<void> {
    await this.db.query('DELETE FROM tickets WHERE id = $1', [id]);
  }

  async removeTicketsByBoard(boardId: string): Promise<void> {
    await this.db.query('DELETE FROM tickets WHERE board_id = $1', [boardId]);
  }

  // ── Agent queries ──

  async getNextTicketForAgent(boardId?: string): Promise<TicketEntity | null> {
    let sql = `SELECT * FROM tickets WHERE status = 'todo' AND blocked = false AND archived_at IS NULL`;
    const params: unknown[] = [];

    if (boardId) {
      params.push(boardId);
      sql += ` AND board_id = $${params.length}`;
    }

    sql += ` ORDER BY
      CASE priority
        WHEN 'high' THEN 0
        WHEN 'medium' THEN 1
        WHEN 'low' THEN 2
        ELSE 3
      END,
      position ASC
      LIMIT 1`;

    const { rows } = await this.db.query(sql, params);
    return rows.length > 0 ? rowToTicket(rows[0]) : null;
  }

  async getClaimedByAgent(agentName: string): Promise<TicketEntity[]> {
    const { rows } = await this.db.query(
      `SELECT * FROM tickets WHERE assignee = $1 AND status = 'doing' AND archived_at IS NULL`,
      [agentName],
    );
    return rows.map(rowToTicket);
  }

  async getArchivedTickets(boardId?: string, limit = 50, offset = 0): Promise<TicketEntity[]> {
    let sql = 'SELECT * FROM tickets WHERE archived_at IS NOT NULL';
    const params: unknown[] = [];
    if (boardId) {
      params.push(boardId);
      sql += ` AND board_id = $${params.length}`;
    }
    params.push(limit, offset);
    sql += ` ORDER BY archived_at DESC LIMIT $${params.length - 1} OFFSET $${params.length}`;
    const { rows } = await this.db.query(sql, params);
    return rows.map(rowToTicket);
  }

  async countArchivedTickets(boardId?: string): Promise<number> {
    let sql = 'SELECT COUNT(*)::int AS count FROM tickets WHERE archived_at IS NOT NULL';
    const params: unknown[] = [];
    if (boardId) {
      params.push(boardId);
      sql += ` AND board_id = $${params.length}`;
    }
    const { rows } = await this.db.query(sql, params);
    return (rows[0]?.count as number) ?? 0;
  }

  // ── Activity ──

  async saveActivity(entry: TicketActivityEntity): Promise<void> {
    await this.db.query(
      `INSERT INTO ticket_activities (id, ticket_id, action, changes, actor_type, actor_name, source, created_at)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
       ON CONFLICT (id) DO UPDATE SET
         ticket_id = $2,
         action = $3,
         changes = $4,
         actor_type = $5,
         actor_name = $6,
         source = $7,
         created_at = $8`,
      [
        entry.id,
        entry.ticketId,
        entry.action,
        JSON.stringify(entry.changes),
        entry.actorType,
        entry.actorName,
        entry.source,
        entry.createdAt.toISOString(),
      ],
    );

    // Cap total activity entries at MAX_ACTIVITY_ENTRIES
    await this.db.query(
      `DELETE FROM ticket_activities WHERE id IN (
        SELECT id FROM ticket_activities ORDER BY created_at DESC OFFSET $1
      )`,
      [MAX_ACTIVITY_ENTRIES],
    );
  }

  async getActivitiesByTicket(ticketId: string, limit = 50): Promise<TicketActivityEntity[]> {
    const { rows } = await this.db.query(
      'SELECT * FROM ticket_activities WHERE ticket_id = $1 ORDER BY created_at DESC LIMIT $2',
      [ticketId, limit],
    );
    return rows.map(rowToActivity);
  }

  async searchTicketsByActivityFilters(options: {
    since?: Date;
    until?: Date;
    action?: string;
    limit?: number;
  }): Promise<TicketActivityEntity[]> {
    const conditions: string[] = [];
    const params: unknown[] = [];

    if (options.since) {
      params.push(options.since.toISOString());
      conditions.push(`created_at >= $${params.length}`);
    }
    if (options.until) {
      params.push(options.until.toISOString());
      conditions.push(`created_at <= $${params.length}`);
    }
    if (options.action) {
      params.push(options.action);
      conditions.push(`action = $${params.length}`);
    }

    const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';
    params.push(options.limit ?? 200);

    const { rows } = await this.db.query(
      `SELECT * FROM ticket_activities ${where} ORDER BY created_at DESC LIMIT $${params.length}`,
      params,
    );
    return rows.map(rowToActivity);
  }
}

function rowToBoard(row: Record<string, unknown>): BoardEntity {
  return new BoardEntity(
    row.id as string,
    row.name as string,
    row.emoji as string,
    new Date(row.created_at as string),
    new Date(row.updated_at as string),
  );
}

function rowToTicket(row: Record<string, unknown>): TicketEntity {
  return new TicketEntity(
    row.id as string,
    row.board_id as string,
    (row.display_id as number) ?? 0,
    row.title as string,
    (row.description as string) ?? '',
    row.status as TicketStatus,
    (row.priority as TicketPriority) ?? 'none',
    (row.type as TicketType | null) ?? null,
    (row.position as number) ?? 0,
    (row.tags as string[]) ?? [],
    (row.links as TicketLink[]) ?? [],
    (row.blocked as boolean) ?? false,
    (row.favorite as boolean) ?? false,
    row.due_date ? new Date(row.due_date as string) : null,
    (row.assignee as string) ?? null,
    row.agent_claimed_at ? new Date(row.agent_claimed_at as string) : null,
    (row.github_metadata as GitHubIssueMetadata) ?? null,
    row.archived_at ? new Date(row.archived_at as string) : null,
    row.first_doing_at ? new Date(row.first_doing_at as string) : null,
    new Date(row.status_changed_at as string),
    new Date(row.created_at as string),
    new Date(row.updated_at as string),
    (row.conversation_mode as ConversationMode | null) ?? 'plan',
    (row.model_override as string | null) ?? null,
    (row.effort_override as EffortLevel | null) ?? null,
    row.fast_mode === true,
  );
}

function rowToActivity(row: Record<string, unknown>): TicketActivityEntity {
  return new TicketActivityEntity(
    row.id as string,
    row.ticket_id as string,
    row.action as string,
    (row.changes as Record<string, { from: unknown; to: unknown }>) ?? {},
    (row.actor_type as 'user' | 'agent') ?? 'user',
    (row.actor_name as string) ?? null,
    (row.source as 'web' | 'api') ?? 'web',
    new Date(row.created_at as string),
  );
}
