/**
 * Golden test for `GetStatisticsUseCase` — the contract this refactor must not
 * break.
 *
 * The use case computes ~15 independent aggregates from 10 stores. Asserting
 * them field by field would take hundreds of brittle expectations, so instead
 * we lock the *entire* `StatisticsResponse` for a fixture that exercises every
 * branch (see `tests/helpers/statistics-fixture.ts`) and diff it on each run.
 *
 * These snapshots were recorded against the pre-refactor implementation and are
 * deliberately never re-recorded: if one moves, behaviour changed. The only
 * intentional delta is documented in the `activeSessions` test at the bottom —
 * and it is provably a no-op, so the snapshots below are unaffected.
 *
 * `buildBuckets` labels months with local-time getters (`getFullYear`,
 * `getMonth`) and advances buckets with `setDate`/`setMonth`, so bucket
 * boundaries depend on the ambient timezone. Pinning `TZ=UTC` here makes the
 * snapshots reproducible on any machine. Vitest isolates each test file in its
 * own process, so this does not leak into the rest of the suite.
 */
process.env['TZ'] = 'UTC';

import { describe, it, expect } from 'vitest';

import { buildFixture, FROM, TO, TZ_OFFSET_MINUTES } from '../helpers/statistics-fixture.js';

describe('GetStatisticsUseCase — golden response', () => {
  it('matches the recorded response at day granularity', async () => {
    const { useCase } = buildFixture();

    const result = await useCase.execute({
      from: FROM,
      to: TO,
      granularity: 'day',
      tzOffsetMinutes: TZ_OFFSET_MINUTES,
    });

    expect(result).toMatchInlineSnapshot(`
      {
        "activityHeatmap": [
          {
            "count": 1,
            "dow": 1,
            "hour": 11,
          },
          {
            "count": 1,
            "dow": 2,
            "hour": 12,
          },
          {
            "count": 1,
            "dow": 3,
            "hour": 16,
          },
          {
            "count": 1,
            "dow": 4,
            "hour": 13,
          },
          {
            "count": 1,
            "dow": 5,
            "hour": 13,
          },
          {
            "count": 1,
            "dow": 6,
            "hour": 22,
          },
          {
            "count": 1,
            "dow": 6,
            "hour": 23,
          },
        ],
        "agentLeaderboard": [
          {
            "avgCostUsd": 0.65,
            "avgDurationMs": 700000,
            "avgInputTokens": 1050,
            "avgOutputTokens": 175,
            "completedCount": 3,
            "failedCount": 0,
            "personaDisplayName": "The Builder",
            "personaId": "p-builder",
            "personaName": "builder",
            "spawnCount": 3,
            "totalCostUsd": 1.95,
            "totalInputTokens": 2100,
            "totalOutputTokens": 350,
          },
          {
            "avgCostUsd": 0.1,
            "avgDurationMs": 120000,
            "avgInputTokens": 10,
            "avgOutputTokens": 5,
            "completedCount": 1,
            "failedCount": 1,
            "personaDisplayName": "The Scout",
            "personaId": "p-scout",
            "personaName": "scout",
            "spawnCount": 2,
            "totalCostUsd": 0.1,
            "totalInputTokens": 10,
            "totalOutputTokens": 5,
          },
          {
            "avgCostUsd": 3,
            "avgDurationMs": 2700000,
            "avgInputTokens": null,
            "avgOutputTokens": null,
            "completedCount": 1,
            "failedCount": 0,
            "personaDisplayName": "cli",
            "personaId": "cli",
            "personaName": "cli",
            "spawnCount": 1,
            "totalCostUsd": 3,
            "totalInputTokens": 0,
            "totalOutputTokens": 0,
          },
          {
            "avgCostUsd": null,
            "avgDurationMs": null,
            "avgInputTokens": null,
            "avgOutputTokens": null,
            "completedCount": 0,
            "failedCount": 0,
            "personaDisplayName": "p-ghost",
            "personaId": "p-ghost",
            "personaName": "p-ghost",
            "spawnCount": 1,
            "totalCostUsd": 0,
            "totalInputTokens": 0,
            "totalOutputTokens": 0,
          },
        ],
        "cumulativeFlow": [
          {
            "backlog": 3,
            "date": "2026-06-01",
            "doing": 1,
            "done": 0,
            "reviewing": 0,
            "todo": 1,
          },
          {
            "backlog": 4,
            "date": "2026-06-02",
            "doing": 2,
            "done": 1,
            "reviewing": 0,
            "todo": 1,
          },
          {
            "backlog": 4,
            "date": "2026-06-03",
            "doing": 3,
            "done": 1,
            "reviewing": 1,
            "todo": 0,
          },
          {
            "backlog": 4,
            "date": "2026-06-04",
            "doing": 2,
            "done": 2,
            "reviewing": 1,
            "todo": 0,
          },
          {
            "backlog": 4,
            "date": "2026-06-05",
            "doing": 2,
            "done": 2,
            "reviewing": 1,
            "todo": 0,
          },
          {
            "backlog": 4,
            "date": "2026-06-06",
            "doing": 1,
            "done": 2,
            "reviewing": 1,
            "todo": 0,
          },
          {
            "backlog": 4,
            "date": "2026-06-07",
            "doing": 1,
            "done": 2,
            "reviewing": 1,
            "todo": 0,
          },
        ],
        "cycleTimeByStatus": [
          {
            "avgMs": 204300000,
            "count": 4,
            "status": "backlog",
          },
          {
            "avgMs": 86400000,
            "count": 1,
            "status": "todo",
          },
          {
            "avgMs": 397800000,
            "count": 2,
            "status": "doing",
          },
          {
            "avgMs": 79200000,
            "count": 1,
            "status": "reviewing",
          },
        ],
        "from": "2026-06-01T00:00:00.000Z",
        "granularity": "day",
        "leadTime": {
          "avgMs": 437400000,
          "medianMs": 698400000,
          "p85Ms": 698400000,
          "points": [
            {
              "doneAt": "2026-06-04T10:00:00.000Z",
              "leadTimeMs": 176400000,
              "ticketId": "aaaaaaaa-0005-4000-8000-000000000000",
              "title": "Done with history",
            },
            {
              "doneAt": "2026-06-02T11:00:00.000Z",
              "leadTimeMs": 698400000,
              "ticketId": "aaaaaaaa-0009-4000-8000-000000000000",
              "title": "Old ticket completed in range",
            },
          ],
        },
        "panelLeaderboard": [
          {
            "avgDurationMs": 6000,
            "avgRespondedMembers": 2.5,
            "completedCount": 2,
            "executionCount": 3,
            "failedCount": 1,
            "panelDisplayName": "Design Review",
            "panelId": "pan1",
            "panelName": "design-review",
          },
          {
            "avgDurationMs": 1000,
            "avgRespondedMembers": 1,
            "completedCount": 1,
            "executionCount": 1,
            "failedCount": 0,
            "panelDisplayName": "pan2",
            "panelId": "pan2",
            "panelName": "pan2",
          },
          {
            "avgDurationMs": 2000,
            "avgRespondedMembers": 4,
            "completedCount": 1,
            "executionCount": 1,
            "failedCount": 0,
            "panelDisplayName": "unknown",
            "panelId": "unknown",
            "panelName": "unknown",
          },
        ],
        "skillLeaderboard": [
          {
            "completedCount": 1,
            "executionCount": 2,
            "failedCount": 1,
            "skillDisplayName": "Spec Writer",
            "skillId": "sk-spec",
            "skillName": "spec",
          },
          {
            "completedCount": 1,
            "executionCount": 1,
            "failedCount": 0,
            "skillDisplayName": "sk-ghost",
            "skillId": "sk-ghost",
            "skillName": "sk-ghost",
          },
        ],
        "summary": {
          "activeSessions": 3,
          "agentsSpawned": 7,
          "avgAgentDurationMs": 984000,
          "commentsCreated": 5,
          "commentsCreatedByAgent": 3,
          "commentsCreatedByUser": 2,
          "deliverablesCreated": 2,
          "mentionsCreated": 3,
          "mentionsResolved": 2,
          "panelsExecuted": 5,
          "prsCreated": 4,
          "prsMerged": 3,
          "skillsExecuted": 3,
          "ticketsCompleted": 3,
          "ticketsCreated": 8,
          "totalCostBySource": {
            "cli": 3,
            "sdk": 2.0500000000000003,
          },
          "totalCostUsd": 5.05,
          "totalInputTokens": 2110,
          "totalOutputTokens": 355,
          "workflowsStarted": 3,
          "worktreesCreated": 3,
        },
        "throughputWip": [
          {
            "completed": 0,
            "date": "2026-06-01",
            "wip": 1,
          },
          {
            "completed": 1,
            "date": "2026-06-02",
            "wip": 2,
          },
          {
            "completed": 1,
            "date": "2026-06-03",
            "wip": 4,
          },
          {
            "completed": 1,
            "date": "2026-06-04",
            "wip": 3,
          },
          {
            "completed": 1,
            "date": "2026-06-05",
            "wip": 3,
          },
          {
            "completed": 0,
            "date": "2026-06-06",
            "wip": 2,
          },
          {
            "completed": 0,
            "date": "2026-06-07",
            "wip": 2,
          },
        ],
        "ticketIterations": [
          {
            "agentRuns": 1,
            "comments": 3,
            "mentions": 1,
            "ticketId": "aaaaaaaa-0005-4000-8000-000000000000",
            "title": "Done with history",
            "total": 6,
            "workflowRuns": 2,
          },
          {
            "agentRuns": 0,
            "comments": 1,
            "mentions": 1,
            "ticketId": "aaaaaaaa-0006-4000-8000-000000000000",
            "title": "Done without history",
            "total": 3,
            "workflowRuns": 1,
          },
          {
            "agentRuns": 0,
            "comments": 0,
            "mentions": 0,
            "ticketId": "aaaaaaaa-0008-4000-8000-000000000000",
            "title": "Done on deleted board",
            "total": 0,
            "workflowRuns": 0,
          },
          {
            "agentRuns": 1,
            "comments": 0,
            "mentions": 1,
            "ticketId": "aaaaaaaa-0009-4000-8000-000000000000",
            "title": "Old ticket completed in range",
            "total": 1,
            "workflowRuns": 0,
          },
        ],
        "timeSeries": [
          {
            "agentsSpawned": 1,
            "commentsCreated": 2,
            "commentsCreatedByAgent": 1,
            "commentsCreatedByUser": 1,
            "costByAgent": {
              "The Builder": 0.5,
            },
            "costBySource": {
              "cli": 0,
              "sdk": 0.5,
            },
            "date": "2026-06-01",
            "deliverablesCreated": 0,
            "mentionsCreated": 1,
            "mentionsResolved": 1,
            "panelsExecuted": 0,
            "prsCreated": 3,
            "prsMerged": 0,
            "skillsExecuted": 0,
            "ticketsCompleted": 2,
            "ticketsCreated": 4,
            "ticketsDoneByBoard": {},
            "totalCostUsd": 0.5,
            "workflowsStarted": 1,
            "worktreesCreated": 1,
          },
          {
            "agentsSpawned": 1,
            "commentsCreated": 1,
            "commentsCreatedByAgent": 0,
            "commentsCreatedByUser": 1,
            "costByAgent": {
              "The Builder": 1.25,
            },
            "costBySource": {
              "cli": 0,
              "sdk": 1.25,
            },
            "date": "2026-06-02",
            "deliverablesCreated": 1,
            "mentionsCreated": 1,
            "mentionsResolved": 0,
            "panelsExecuted": 1,
            "prsCreated": 1,
            "prsMerged": 1,
            "skillsExecuted": 0,
            "ticketsCompleted": 0,
            "ticketsCreated": 3,
            "ticketsDoneByBoard": {
              "Backend": 1,
            },
            "totalCostUsd": 1.25,
            "workflowsStarted": 1,
            "worktreesCreated": 0,
          },
          {
            "agentsSpawned": 1,
            "commentsCreated": 1,
            "commentsCreatedByAgent": 1,
            "commentsCreatedByUser": 0,
            "costByAgent": {
              "cli": 3,
            },
            "costBySource": {
              "cli": 3,
              "sdk": 0,
            },
            "date": "2026-06-03",
            "deliverablesCreated": 0,
            "mentionsCreated": 0,
            "mentionsResolved": 0,
            "panelsExecuted": 1,
            "prsCreated": 0,
            "prsMerged": 1,
            "skillsExecuted": 0,
            "ticketsCompleted": 1,
            "ticketsCreated": 1,
            "ticketsDoneByBoard": {
              "Unknown": 1,
            },
            "totalCostUsd": 3,
            "workflowsStarted": 1,
            "worktreesCreated": 1,
          },
          {
            "agentsSpawned": 1,
            "commentsCreated": 0,
            "commentsCreatedByAgent": 0,
            "commentsCreatedByUser": 0,
            "costByAgent": {},
            "costBySource": {
              "cli": 0,
              "sdk": 0,
            },
            "date": "2026-06-04",
            "deliverablesCreated": 1,
            "mentionsCreated": 0,
            "mentionsResolved": 0,
            "panelsExecuted": 1,
            "prsCreated": 0,
            "prsMerged": 1,
            "skillsExecuted": 1,
            "ticketsCompleted": 0,
            "ticketsCreated": 0,
            "ticketsDoneByBoard": {
              "Backend": 1,
            },
            "totalCostUsd": 0,
            "workflowsStarted": 0,
            "worktreesCreated": 1,
          },
          {
            "agentsSpawned": 1,
            "commentsCreated": 1,
            "commentsCreatedByAgent": 1,
            "commentsCreatedByUser": 0,
            "costByAgent": {
              "The Scout": 0.1,
            },
            "costBySource": {
              "cli": 0,
              "sdk": 0.1,
            },
            "date": "2026-06-05",
            "deliverablesCreated": 0,
            "mentionsCreated": 1,
            "mentionsResolved": 1,
            "panelsExecuted": 1,
            "prsCreated": 0,
            "prsMerged": 0,
            "skillsExecuted": 1,
            "ticketsCompleted": 0,
            "ticketsCreated": 0,
            "ticketsDoneByBoard": {
              "Ops": 1,
            },
            "totalCostUsd": 0.1,
            "workflowsStarted": 0,
            "worktreesCreated": 0,
          },
          {
            "agentsSpawned": 2,
            "commentsCreated": 0,
            "commentsCreatedByAgent": 0,
            "commentsCreatedByUser": 0,
            "costByAgent": {
              "The Builder": 0.2,
            },
            "costBySource": {
              "cli": 0,
              "sdk": 0.2,
            },
            "date": "2026-06-06",
            "deliverablesCreated": 0,
            "mentionsCreated": 0,
            "mentionsResolved": 0,
            "panelsExecuted": 1,
            "prsCreated": 0,
            "prsMerged": 0,
            "skillsExecuted": 1,
            "ticketsCompleted": 0,
            "ticketsCreated": 0,
            "ticketsDoneByBoard": {},
            "totalCostUsd": 0.2,
            "workflowsStarted": 0,
            "worktreesCreated": 0,
          },
          {
            "agentsSpawned": 0,
            "commentsCreated": 0,
            "commentsCreatedByAgent": 0,
            "commentsCreatedByUser": 0,
            "costByAgent": {},
            "costBySource": {
              "cli": 0,
              "sdk": 0,
            },
            "date": "2026-06-07",
            "deliverablesCreated": 0,
            "mentionsCreated": 0,
            "mentionsResolved": 0,
            "panelsExecuted": 0,
            "prsCreated": 0,
            "prsMerged": 0,
            "skillsExecuted": 0,
            "ticketsCompleted": 0,
            "ticketsCreated": 0,
            "ticketsDoneByBoard": {},
            "totalCostUsd": 0,
            "workflowsStarted": 0,
            "worktreesCreated": 0,
          },
        ],
        "to": "2026-06-08T00:00:00.000Z",
        "usageByType": [
          {
            "agents": 1,
            "date": "2026-06-01",
            "panels": 0,
            "skills": 0,
            "workflows": 1,
          },
          {
            "agents": 1,
            "date": "2026-06-02",
            "panels": 1,
            "skills": 0,
            "workflows": 1,
          },
          {
            "agents": 1,
            "date": "2026-06-03",
            "panels": 1,
            "skills": 0,
            "workflows": 1,
          },
          {
            "agents": 0,
            "date": "2026-06-04",
            "panels": 1,
            "skills": 1,
            "workflows": 0,
          },
          {
            "agents": 0,
            "date": "2026-06-05",
            "panels": 1,
            "skills": 1,
            "workflows": 0,
          },
          {
            "agents": 1,
            "date": "2026-06-06",
            "panels": 1,
            "skills": 1,
            "workflows": 0,
          },
          {
            "agents": 0,
            "date": "2026-06-07",
            "panels": 0,
            "skills": 0,
            "workflows": 0,
          },
        ],
        "workflowLeaderboard": [
          {
            "avgDurationMs": 3600000,
            "completedCount": 1,
            "executionCount": 2,
            "failedCount": 1,
            "workflowDisplayName": "Ship it",
            "workflowId": "tpl-a",
            "workflowName": "Ship it",
          },
          {
            "avgDurationMs": 1800000,
            "completedCount": 1,
            "executionCount": 1,
            "failedCount": 0,
            "workflowDisplayName": "Review it",
            "workflowId": "tpl-b",
            "workflowName": "Review it",
          },
        ],
      }
    `);
  });

  it('matches the recorded response at week granularity', async () => {
    const { useCase } = buildFixture();

    const result = await useCase.execute({
      from: FROM,
      to: TO,
      granularity: 'week',
      tzOffsetMinutes: TZ_OFFSET_MINUTES,
    });

    expect(result).toMatchInlineSnapshot(`
      {
        "activityHeatmap": [
          {
            "count": 1,
            "dow": 1,
            "hour": 11,
          },
          {
            "count": 1,
            "dow": 2,
            "hour": 12,
          },
          {
            "count": 1,
            "dow": 3,
            "hour": 16,
          },
          {
            "count": 1,
            "dow": 4,
            "hour": 13,
          },
          {
            "count": 1,
            "dow": 5,
            "hour": 13,
          },
          {
            "count": 1,
            "dow": 6,
            "hour": 22,
          },
          {
            "count": 1,
            "dow": 6,
            "hour": 23,
          },
        ],
        "agentLeaderboard": [
          {
            "avgCostUsd": 0.65,
            "avgDurationMs": 700000,
            "avgInputTokens": 1050,
            "avgOutputTokens": 175,
            "completedCount": 3,
            "failedCount": 0,
            "personaDisplayName": "The Builder",
            "personaId": "p-builder",
            "personaName": "builder",
            "spawnCount": 3,
            "totalCostUsd": 1.95,
            "totalInputTokens": 2100,
            "totalOutputTokens": 350,
          },
          {
            "avgCostUsd": 0.1,
            "avgDurationMs": 120000,
            "avgInputTokens": 10,
            "avgOutputTokens": 5,
            "completedCount": 1,
            "failedCount": 1,
            "personaDisplayName": "The Scout",
            "personaId": "p-scout",
            "personaName": "scout",
            "spawnCount": 2,
            "totalCostUsd": 0.1,
            "totalInputTokens": 10,
            "totalOutputTokens": 5,
          },
          {
            "avgCostUsd": 3,
            "avgDurationMs": 2700000,
            "avgInputTokens": null,
            "avgOutputTokens": null,
            "completedCount": 1,
            "failedCount": 0,
            "personaDisplayName": "cli",
            "personaId": "cli",
            "personaName": "cli",
            "spawnCount": 1,
            "totalCostUsd": 3,
            "totalInputTokens": 0,
            "totalOutputTokens": 0,
          },
          {
            "avgCostUsd": null,
            "avgDurationMs": null,
            "avgInputTokens": null,
            "avgOutputTokens": null,
            "completedCount": 0,
            "failedCount": 0,
            "personaDisplayName": "p-ghost",
            "personaId": "p-ghost",
            "personaName": "p-ghost",
            "spawnCount": 1,
            "totalCostUsd": 0,
            "totalInputTokens": 0,
            "totalOutputTokens": 0,
          },
        ],
        "cumulativeFlow": [
          {
            "backlog": 4,
            "date": "2026-06-01",
            "doing": 1,
            "done": 2,
            "reviewing": 1,
            "todo": 0,
          },
        ],
        "cycleTimeByStatus": [
          {
            "avgMs": 204300000,
            "count": 4,
            "status": "backlog",
          },
          {
            "avgMs": 86400000,
            "count": 1,
            "status": "todo",
          },
          {
            "avgMs": 397800000,
            "count": 2,
            "status": "doing",
          },
          {
            "avgMs": 79200000,
            "count": 1,
            "status": "reviewing",
          },
        ],
        "from": "2026-06-01T00:00:00.000Z",
        "granularity": "week",
        "leadTime": {
          "avgMs": 437400000,
          "medianMs": 698400000,
          "p85Ms": 698400000,
          "points": [
            {
              "doneAt": "2026-06-04T10:00:00.000Z",
              "leadTimeMs": 176400000,
              "ticketId": "aaaaaaaa-0005-4000-8000-000000000000",
              "title": "Done with history",
            },
            {
              "doneAt": "2026-06-02T11:00:00.000Z",
              "leadTimeMs": 698400000,
              "ticketId": "aaaaaaaa-0009-4000-8000-000000000000",
              "title": "Old ticket completed in range",
            },
          ],
        },
        "panelLeaderboard": [
          {
            "avgDurationMs": 6000,
            "avgRespondedMembers": 2.5,
            "completedCount": 2,
            "executionCount": 3,
            "failedCount": 1,
            "panelDisplayName": "Design Review",
            "panelId": "pan1",
            "panelName": "design-review",
          },
          {
            "avgDurationMs": 1000,
            "avgRespondedMembers": 1,
            "completedCount": 1,
            "executionCount": 1,
            "failedCount": 0,
            "panelDisplayName": "pan2",
            "panelId": "pan2",
            "panelName": "pan2",
          },
          {
            "avgDurationMs": 2000,
            "avgRespondedMembers": 4,
            "completedCount": 1,
            "executionCount": 1,
            "failedCount": 0,
            "panelDisplayName": "unknown",
            "panelId": "unknown",
            "panelName": "unknown",
          },
        ],
        "skillLeaderboard": [
          {
            "completedCount": 1,
            "executionCount": 2,
            "failedCount": 1,
            "skillDisplayName": "Spec Writer",
            "skillId": "sk-spec",
            "skillName": "spec",
          },
          {
            "completedCount": 1,
            "executionCount": 1,
            "failedCount": 0,
            "skillDisplayName": "sk-ghost",
            "skillId": "sk-ghost",
            "skillName": "sk-ghost",
          },
        ],
        "summary": {
          "activeSessions": 3,
          "agentsSpawned": 7,
          "avgAgentDurationMs": 984000,
          "commentsCreated": 5,
          "commentsCreatedByAgent": 3,
          "commentsCreatedByUser": 2,
          "deliverablesCreated": 2,
          "mentionsCreated": 3,
          "mentionsResolved": 2,
          "panelsExecuted": 5,
          "prsCreated": 4,
          "prsMerged": 3,
          "skillsExecuted": 3,
          "ticketsCompleted": 3,
          "ticketsCreated": 8,
          "totalCostBySource": {
            "cli": 3,
            "sdk": 2.0500000000000003,
          },
          "totalCostUsd": 5.05,
          "totalInputTokens": 2110,
          "totalOutputTokens": 355,
          "workflowsStarted": 3,
          "worktreesCreated": 3,
        },
        "throughputWip": [
          {
            "completed": 4,
            "date": "2026-06-01",
            "wip": 2,
          },
        ],
        "ticketIterations": [
          {
            "agentRuns": 1,
            "comments": 3,
            "mentions": 1,
            "ticketId": "aaaaaaaa-0005-4000-8000-000000000000",
            "title": "Done with history",
            "total": 6,
            "workflowRuns": 2,
          },
          {
            "agentRuns": 0,
            "comments": 1,
            "mentions": 1,
            "ticketId": "aaaaaaaa-0006-4000-8000-000000000000",
            "title": "Done without history",
            "total": 3,
            "workflowRuns": 1,
          },
          {
            "agentRuns": 0,
            "comments": 0,
            "mentions": 0,
            "ticketId": "aaaaaaaa-0008-4000-8000-000000000000",
            "title": "Done on deleted board",
            "total": 0,
            "workflowRuns": 0,
          },
          {
            "agentRuns": 1,
            "comments": 0,
            "mentions": 1,
            "ticketId": "aaaaaaaa-0009-4000-8000-000000000000",
            "title": "Old ticket completed in range",
            "total": 1,
            "workflowRuns": 0,
          },
        ],
        "timeSeries": [
          {
            "agentsSpawned": 7,
            "commentsCreated": 5,
            "commentsCreatedByAgent": 3,
            "commentsCreatedByUser": 2,
            "costByAgent": {
              "The Builder": 1.95,
              "The Scout": 0.1,
              "cli": 3,
            },
            "costBySource": {
              "cli": 3,
              "sdk": 2.0500000000000003,
            },
            "date": "2026-06-01",
            "deliverablesCreated": 2,
            "mentionsCreated": 3,
            "mentionsResolved": 2,
            "panelsExecuted": 5,
            "prsCreated": 4,
            "prsMerged": 3,
            "skillsExecuted": 3,
            "ticketsCompleted": 3,
            "ticketsCreated": 8,
            "ticketsDoneByBoard": {
              "Backend": 2,
              "Ops": 1,
              "Unknown": 1,
            },
            "totalCostUsd": 5.05,
            "workflowsStarted": 3,
            "worktreesCreated": 3,
          },
        ],
        "to": "2026-06-08T00:00:00.000Z",
        "usageByType": [
          {
            "agents": 4,
            "date": "2026-06-01",
            "panels": 5,
            "skills": 3,
            "workflows": 3,
          },
        ],
        "workflowLeaderboard": [
          {
            "avgDurationMs": 3600000,
            "completedCount": 1,
            "executionCount": 2,
            "failedCount": 1,
            "workflowDisplayName": "Ship it",
            "workflowId": "tpl-a",
            "workflowName": "Ship it",
          },
          {
            "avgDurationMs": 1800000,
            "completedCount": 1,
            "executionCount": 1,
            "failedCount": 0,
            "workflowDisplayName": "Review it",
            "workflowId": "tpl-b",
            "workflowName": "Review it",
          },
        ],
      }
    `);
  });

  it('matches the recorded response at month granularity', async () => {
    const { useCase } = buildFixture();

    const result = await useCase.execute({
      // Widened so the month bucket is not degenerate, and so the final bucket
      // is clamped to `to` mid-month.
      from: '2026-05-15T00:00:00.000Z',
      to: '2026-06-20T00:00:00.000Z',
      granularity: 'month',
      tzOffsetMinutes: TZ_OFFSET_MINUTES,
    });

    expect(result).toMatchInlineSnapshot(`
      {
        "activityHeatmap": [
          {
            "count": 1,
            "dow": 1,
            "hour": 11,
          },
          {
            "count": 1,
            "dow": 2,
            "hour": 12,
          },
          {
            "count": 1,
            "dow": 3,
            "hour": 16,
          },
          {
            "count": 1,
            "dow": 4,
            "hour": 13,
          },
          {
            "count": 1,
            "dow": 5,
            "hour": 13,
          },
          {
            "count": 1,
            "dow": 6,
            "hour": 22,
          },
          {
            "count": 1,
            "dow": 6,
            "hour": 23,
          },
          {
            "count": 1,
            "dow": 6,
            "hour": 11,
          },
        ],
        "agentLeaderboard": [
          {
            "avgCostUsd": 2.7375,
            "avgDurationMs": 675000,
            "avgInputTokens": 1050,
            "avgOutputTokens": 175,
            "completedCount": 4,
            "failedCount": 0,
            "personaDisplayName": "The Builder",
            "personaId": "p-builder",
            "personaName": "builder",
            "spawnCount": 4,
            "totalCostUsd": 10.95,
            "totalInputTokens": 2100,
            "totalOutputTokens": 350,
          },
          {
            "avgCostUsd": 0.1,
            "avgDurationMs": 120000,
            "avgInputTokens": 10,
            "avgOutputTokens": 5,
            "completedCount": 1,
            "failedCount": 1,
            "personaDisplayName": "The Scout",
            "personaId": "p-scout",
            "personaName": "scout",
            "spawnCount": 2,
            "totalCostUsd": 0.1,
            "totalInputTokens": 10,
            "totalOutputTokens": 5,
          },
          {
            "avgCostUsd": 3,
            "avgDurationMs": 2700000,
            "avgInputTokens": null,
            "avgOutputTokens": null,
            "completedCount": 1,
            "failedCount": 0,
            "personaDisplayName": "cli",
            "personaId": "cli",
            "personaName": "cli",
            "spawnCount": 1,
            "totalCostUsd": 3,
            "totalInputTokens": 0,
            "totalOutputTokens": 0,
          },
          {
            "avgCostUsd": null,
            "avgDurationMs": null,
            "avgInputTokens": null,
            "avgOutputTokens": null,
            "completedCount": 0,
            "failedCount": 0,
            "personaDisplayName": "p-ghost",
            "personaId": "p-ghost",
            "personaName": "p-ghost",
            "spawnCount": 1,
            "totalCostUsd": 0,
            "totalInputTokens": 0,
            "totalOutputTokens": 0,
          },
        ],
        "cumulativeFlow": [
          {
            "backlog": 5,
            "date": "2026-05",
            "doing": 1,
            "done": 2,
            "reviewing": 1,
            "todo": 0,
          },
          {
            "backlog": 5,
            "date": "2026-06",
            "doing": 1,
            "done": 2,
            "reviewing": 1,
            "todo": 0,
          },
        ],
        "cycleTimeByStatus": [
          {
            "avgMs": 204300000,
            "count": 4,
            "status": "backlog",
          },
          {
            "avgMs": 86400000,
            "count": 1,
            "status": "todo",
          },
          {
            "avgMs": 397800000,
            "count": 2,
            "status": "doing",
          },
          {
            "avgMs": 79200000,
            "count": 1,
            "status": "reviewing",
          },
        ],
        "from": "2026-05-15T00:00:00.000Z",
        "granularity": "month",
        "leadTime": {
          "avgMs": 437400000,
          "medianMs": 698400000,
          "p85Ms": 698400000,
          "points": [
            {
              "doneAt": "2026-06-04T10:00:00.000Z",
              "leadTimeMs": 176400000,
              "ticketId": "aaaaaaaa-0005-4000-8000-000000000000",
              "title": "Done with history",
            },
            {
              "doneAt": "2026-06-02T11:00:00.000Z",
              "leadTimeMs": 698400000,
              "ticketId": "aaaaaaaa-0009-4000-8000-000000000000",
              "title": "Old ticket completed in range",
            },
          ],
        },
        "panelLeaderboard": [
          {
            "avgDurationMs": 6000,
            "avgRespondedMembers": 2.5,
            "completedCount": 2,
            "executionCount": 3,
            "failedCount": 1,
            "panelDisplayName": "Design Review",
            "panelId": "pan1",
            "panelName": "design-review",
          },
          {
            "avgDurationMs": 1000,
            "avgRespondedMembers": 1,
            "completedCount": 1,
            "executionCount": 1,
            "failedCount": 0,
            "panelDisplayName": "pan2",
            "panelId": "pan2",
            "panelName": "pan2",
          },
          {
            "avgDurationMs": 2000,
            "avgRespondedMembers": 4,
            "completedCount": 1,
            "executionCount": 1,
            "failedCount": 0,
            "panelDisplayName": "unknown",
            "panelId": "unknown",
            "panelName": "unknown",
          },
        ],
        "skillLeaderboard": [
          {
            "completedCount": 1,
            "executionCount": 2,
            "failedCount": 1,
            "skillDisplayName": "Spec Writer",
            "skillId": "sk-spec",
            "skillName": "spec",
          },
          {
            "completedCount": 1,
            "executionCount": 1,
            "failedCount": 0,
            "skillDisplayName": "sk-ghost",
            "skillId": "sk-ghost",
            "skillName": "sk-ghost",
          },
        ],
        "summary": {
          "activeSessions": 3,
          "agentsSpawned": 8,
          "avgAgentDurationMs": 920000,
          "commentsCreated": 6,
          "commentsCreatedByAgent": 3,
          "commentsCreatedByUser": 3,
          "deliverablesCreated": 2,
          "mentionsCreated": 4,
          "mentionsResolved": 3,
          "panelsExecuted": 5,
          "prsCreated": 5,
          "prsMerged": 3,
          "skillsExecuted": 3,
          "ticketsCompleted": 4,
          "ticketsCreated": 10,
          "totalCostBySource": {
            "cli": 3,
            "sdk": 11.05,
          },
          "totalCostUsd": 14.05,
          "totalInputTokens": 2110,
          "totalOutputTokens": 355,
          "workflowsStarted": 4,
          "worktreesCreated": 4,
        },
        "throughputWip": [
          {
            "completed": 4,
            "date": "2026-05",
            "wip": 2,
          },
          {
            "completed": 0,
            "date": "2026-06",
            "wip": 2,
          },
        ],
        "ticketIterations": [
          {
            "agentRuns": 1,
            "comments": 3,
            "mentions": 1,
            "ticketId": "aaaaaaaa-0005-4000-8000-000000000000",
            "title": "Done with history",
            "total": 6,
            "workflowRuns": 2,
          },
          {
            "agentRuns": 0,
            "comments": 1,
            "mentions": 1,
            "ticketId": "aaaaaaaa-0006-4000-8000-000000000000",
            "title": "Done without history",
            "total": 3,
            "workflowRuns": 1,
          },
          {
            "agentRuns": 0,
            "comments": 0,
            "mentions": 0,
            "ticketId": "aaaaaaaa-0008-4000-8000-000000000000",
            "title": "Done on deleted board",
            "total": 0,
            "workflowRuns": 0,
          },
          {
            "agentRuns": 1,
            "comments": 0,
            "mentions": 1,
            "ticketId": "aaaaaaaa-0009-4000-8000-000000000000",
            "title": "Old ticket completed in range",
            "total": 1,
            "workflowRuns": 0,
          },
        ],
        "timeSeries": [
          {
            "agentsSpawned": 8,
            "commentsCreated": 6,
            "commentsCreatedByAgent": 3,
            "commentsCreatedByUser": 3,
            "costByAgent": {
              "The Builder": 10.95,
              "The Scout": 0.1,
              "cli": 3,
            },
            "costBySource": {
              "cli": 3,
              "sdk": 11.05,
            },
            "date": "2026-05",
            "deliverablesCreated": 2,
            "mentionsCreated": 4,
            "mentionsResolved": 3,
            "panelsExecuted": 5,
            "prsCreated": 5,
            "prsMerged": 3,
            "skillsExecuted": 3,
            "ticketsCompleted": 4,
            "ticketsCreated": 10,
            "ticketsDoneByBoard": {
              "Backend": 2,
              "Ops": 1,
              "Unknown": 1,
            },
            "totalCostUsd": 14.05,
            "workflowsStarted": 4,
            "worktreesCreated": 4,
          },
          {
            "agentsSpawned": 0,
            "commentsCreated": 0,
            "commentsCreatedByAgent": 0,
            "commentsCreatedByUser": 0,
            "costByAgent": {},
            "costBySource": {
              "cli": 0,
              "sdk": 0,
            },
            "date": "2026-06",
            "deliverablesCreated": 0,
            "mentionsCreated": 0,
            "mentionsResolved": 0,
            "panelsExecuted": 0,
            "prsCreated": 0,
            "prsMerged": 0,
            "skillsExecuted": 0,
            "ticketsCompleted": 0,
            "ticketsCreated": 0,
            "ticketsDoneByBoard": {},
            "totalCostUsd": 0,
            "workflowsStarted": 0,
            "worktreesCreated": 0,
          },
        ],
        "to": "2026-06-20T00:00:00.000Z",
        "usageByType": [
          {
            "agents": 5,
            "date": "2026-05",
            "panels": 5,
            "skills": 3,
            "workflows": 4,
          },
          {
            "agents": 0,
            "date": "2026-06",
            "panels": 0,
            "skills": 0,
            "workflows": 0,
          },
        ],
        "workflowLeaderboard": [
          {
            "avgDurationMs": 3600000,
            "completedCount": 1,
            "executionCount": 2,
            "failedCount": 1,
            "workflowDisplayName": "Ship it",
            "workflowId": "tpl-a",
            "workflowName": "Ship it",
          },
          {
            "avgDurationMs": 2700000,
            "completedCount": 2,
            "executionCount": 2,
            "failedCount": 0,
            "workflowDisplayName": "Review it",
            "workflowId": "tpl-b",
            "workflowName": "Review it",
          },
        ],
      }
    `);
  });
});

// ── AC3: the one permitted behaviour delta ─────────────────────────────────

describe('GetStatisticsUseCase — activeSessions', () => {
  /**
   * The original code read `status === 'active' || status === 'running'` through
   * an `as unknown as Record<string, unknown>` cast. `SessionStatus` is
   * `'running' | 'dead' | 'unknown'` — there has never been an `'active'`
   * member, so the first comparison was unreachable and the cast is all that
   * let it compile. Dropping it is output-neutral, which is exactly what this
   * test pins: only `'running'` sessions count, and the golden snapshots above
   * must not move.
   */
  it('counts only running sessions, ignoring dead and unknown ones', async () => {
    const { useCase, sessions } = buildFixture();

    const result = await useCase.execute({
      from: FROM,
      to: TO,
      granularity: 'day',
      tzOffsetMinutes: TZ_OFFSET_MINUTES,
    });

    const running = sessions.filter((s) => s.status === 'running');
    expect(running).toHaveLength(3);
    expect(sessions.some((s) => s.status === 'dead')).toBe(true);
    expect(sessions.some((s) => s.status === 'unknown')).toBe(true);
    // Counted across *all* sessions, not just those created inside the window.
    expect(result.summary.activeSessions).toBe(3);
  });
});
